# Generated by Django 5.2.8 on 2025-11-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="person",
            options={
                "ordering": ["last_name", "first_name", "middle_name"],
                "verbose_name": "Человек",
                "verbose_name_plural": "Люди",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="middle_name",
            field=models.CharField(
                default="Иванович", max_length=100, verbose_name="Отчество"
            ),
            preserve_default=False,
        ),
    ]
