# Generated by Django 5.2.8 on 2025-11-18 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0002_alter_person_options_person_middle_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="death_date",
            field=models.DateField(blank=True, null=True, verbose_name="Дата смерти"),
        ),
        migrations.AddField(
            model_name="person",
            name="job_title",
            field=models.CharField(
                default="настоятель", max_length=100, verbose_name="Должность"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="rank",
            field=models.CharField(
                default="протоиерей", max_length=100, verbose_name="Сан"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="person",
            name="work_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания работы"
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="work_start_date",
            field=models.DateField(default=datetime.datetime(1990, 11, 18, 22, 4, 34, 368016), verbose_name="Дата начала работы"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="person",
            name="birth_date",
            field=models.DateField(
                default=datetime.datetime(2025, 11, 18, 22, 4, 34, 368016),
                verbose_name="Дата рождения",
            ),
            preserve_default=False,
        ),
    ]
