# Generated by Django 5.2.8 on 2025-11-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="work_start_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Дата начала работы"
            ),
        ),
    ]
