# Generated by Django 5.2.8 on 2025-11-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0002_alter_person_work_start_year"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название группы"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="person",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                related_name="persons",
                to="museum.group",
                verbose_name="Группы",
            ),
        ),
    ]
