# Generated by Django 5.2.8 on 2025-11-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0003_group_person_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="group",
            options={
                "ordering": ["title"],
                "verbose_name": "Группа",
                "verbose_name_plural": "Группы",
            },
        ),
        migrations.RenameField(
            model_name="group",
            old_name="name",
            new_name="title",
        ),
    ]
