# Generated by Django 5.2.8 on 2025-11-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("museum", "0004_alter_group_options_rename_name_group_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="middle_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Отчество"
            ),
        ),
    ]
